@startuml

class humanoid {
  -name : string
  -age : integer u16
  -size : enum size string
  -speed : integer u8
  -hitPoints : integer u16
  -proficiencyBonus : integer u8

  -appearance : struct appearance
    -heigthCm : integer u16
    -weigth : integer u16
    -hair : string
    -skin : string
    -eyes : string
  -personality : struct personality
    -personalityTraits : string
    -ideals : string
    -bonds : string
    -flaws : string
    -alignment : enum alignment string
  -stats : struct stats
    -strength : integer
    -dexterity : integer
    -constitution : integer
    -intelligence : integer
    -wisdom : integer
    -charisma : integer
  -languages : vector<enum language string>
  -proficiencies : vector<enum proficiency string>
  -savingThrows : vector<enum saves string>
  -skills : struct skills // omdat je ook expert kunt zijn struct
}

class race {

}

class subRace {

}

class profesion {

}

class

@enduml